const UrlConfig = {
    authentication: {
        google: "/api/auth/google",
        login: "/api/auth/login",
        refreshToken: "/api/auth/refresh-token",
        register: "/api/auth/register",
        // logout: '/api/auth/logout',
    },
    account: {
        getById: "/api/account/{id}",
        delete: "/api/account/{id}",
        resetPassword: "/api/account/reset-password",
        getAll: "/api/account",
        create: "/api/account",
        update: "/api/account",
        lockUnlock: "/api/account",
        deleteMultiple: "/api/account",
    },
    category: {
        getById: "/api/category/{id}",
        delete: "/api/category/{id}",
        getAll: "/api/category",
        create: "/api/category",
        update: "/api/category",
        deleteMultiple: "/api/category",
        getByIdWithFlowers: "/api/category/with-flowers/{categoryId}",
        getAllWithFlowers: "/api/category/with-flowers",
    },
    feedback: {
        getRecentlyAll: "/api/feedback/recently",
        getAll: "/api/feedback",
        create: "/api/feedback",
        update: "/api/feedback",
        updateLikes: "/api/feedback",
    },
    flower: {
        getFeedbacksOfFlower: "/api/flower/{id}/feedback",
        getById: "/api/flower/{id}",
        delete: "/api/flower/{id}",
        getBestSeller: "/api/flower/best-seller",
        getDecoration: "/api/flower/decoration",
        getGift: "/api/flower/gift",
        getAll: "/api/flower",
        create: "/api/flower",
        update: "/api/flower",
        deleteMultiple: "/api/flower",
        getSuggest: "/api/flower/suggest",
    },
    order: {
        getById: "/api/order/{id}",
        delete: "/api/order/{id}",
        getAll: "/api/order",
        create: "/api/order",
        update: "/api/order",
        deleteMultiple: "/api/order",
    },
    user: {
        deleteCart: "/api/user/cart/{id}",
        getCarts: "/api/user/cart",
        createCart: "/api/user/cart",
        updateCart: "/api/user/cart",
        deleteCarts: "/api/user/cart",
        changePassword: "/api/user/change-password",
        getFavouriteFlower: "/api/user/favourite-flower",
        forgotPassword: "/api/user/forgot-password",
        getAllIdentification: "/api/user/identification",
        getAllOrder: "/api/user/order",
        resetPassword: "/api/user/reset-password",
        getProfile: "/api/user",
        updateProfile: "/api/user",
    },
};

export default UrlConfig;
